const foreach = (idosos)=>{
    idosos.forEach(function(item){
        console.log("nome:"+ item.nome)
    })   
}

const map = (idosos)=>{
    return idosos.map(function (item){
        return item.nome
    })
}

const filter = (idosos)=>{
    return idosos.filter(function(item){
        return item.idade >70 
    })
}

//PERGUNTA:
//QUAL A DIFERENÇA ENTRE CADA UMA DAS FUNÇÕES ACIMA: (FOREACH, MAP, FILTER)

//FOREACH:
// O FOREACH SOMENTE PERCORRE O ARRAY SEM RETORNAR NENHUM VALOR, SERVE APENAS PARA REALIZAR VERIFICAÇÕES, 
//COMO POR EXEMPLO: SE ALGO EXISTE DENTRO DO ARRAY, MAS SEM RETORNAR ESTE ALGO.

//MAP:
//O MAP FAZ A MESMA FUNÇÃO DO FOREACH, OU SEJA PERCORRE O ARRAY, CONSEGUE REALIZAR VERIFICAÇÕES DENTRO DELA, MAS O MAP PERMITE
//RETORNAR VALORES, CONSEQUENTEMENTE É POSSÍVEL VERIFICAR SE ALGO EXISTE E RETORNAR ESTE ALGO, OU ATÉ MESMO CRIAR UM OUTRO
//ARRAY À PARTIR DO ARRAY VERIFICADO

//FILTER:
//O FILTER PERCORRE TODO O VETOR E RETORNAR TODO O OBJETO QUE ATENDE AO REQUISITO DO FILTRO
//A DIFERENÇA ENTRE O FLITER E O MAP (JÁ QUE PODE SER FEITO UM FILTRO DENTRO DO MAP, ATRAVÉS DE IF's) O MAP PODE RETORNAR 
//SOMENTE UM ATRIBUTO, JÁ O FILTER RETORNAR TODO O OBJETO CONTIDO NO ARRAY.

