/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forca;

import java.awt.FlowLayout;
import java.awt.Font;
import java.util.HashSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author CarlosGuilhermeHackb
 */
public class ForcaWindow extends javax.swing.JFrame {
    
    private String palavra;
    private int tamanhoPalavra;
    private int quantidadeErros;
    private int quantidadeAcertos;
    private JButton[] botoes;
    private char[] arrayChars;
    
    /**
     * Creates new form ForcaWindow
     */
    public ForcaWindow() {
        initComponents();
        getText();
        iniciarVariaveis();
        iniciaBotoes();
        this.pack();
    }
    
    private void getText(){
        this.palavra = JOptionPane.showInputDialog("Digite a palavra");
        this.tamanhoPalavra = palavra.length();
    }
    
    private void iniciarVariaveis(){
        this.quantidadeErros = 0;
        this.quantidadeAcertos = 0;
        this.arrayChars = palavra.toCharArray();
    }
    
    private void iniciaBotoes(){
        this.botoes = new JButton[this.tamanhoPalavra];
        painelPalavra.setLayout(new FlowLayout());
        
        for(int i = 0; i < this.tamanhoPalavra; i++){
            this.botoes[i] = new JButton(" ");
            this.botoes[i].setFont(new Font("Comic Sans", Font.PLAIN, 50));
            this.botoes[i].setEnabled(false);
            
            painelPalavra.add(this.botoes[i]);
        }
    }
    
    private void verificarPalpite(char letra){
        boolean encontrou = false;
        for(int i = 0; i < this.tamanhoPalavra; i++){
            if(this.arrayChars[i] == letra){
                this.botoes[i].setText(letra + "");
                this.quantidadeAcertos++;
                winGame(this.quantidadeAcertos);
                encontrou = true;
            }
        }
        
        if(!encontrou){
            marcarErro(letra + "");
        }
        
        limparTxtLetra();
    }
    
    private void limparTxtLetra(){
        txtLetra.setText("");
    }
    
    private void marcarErro(String erro){
        txtErros.setText(txtErros.getText() + " " + erro);
        
        this.quantidadeErros++;
        
        gameOver(this.quantidadeErros);
    }
    
    private void gameOver(int quantidade){
        if(quantidade == 5){
            JOptionPane.showMessageDialog(this, "Game Over");
            btnVerificar.setEnabled(false);
        }
    }
    
    private void winGame(int quantidade){
        if(quantidade == this.tamanhoPalavra){
            JOptionPane.showMessageDialog(this, "Parabéns Campeão!");
            btnVerificar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtLetra = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtErros = new javax.swing.JTextField();
        painelPalavra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Letra"));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 5));
        jPanel3.add(txtLetra);

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnVerificar);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setText("Erros");
        jPanel4.add(jLabel1);
        jPanel4.add(txtErros);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        painelPalavra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Palavra"));

        javax.swing.GroupLayout painelPalavraLayout = new javax.swing.GroupLayout(painelPalavra);
        painelPalavra.setLayout(painelPalavraLayout);
        painelPalavraLayout.setHorizontalGroup(
            painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        painelPalavraLayout.setVerticalGroup(
            painelPalavraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        getContentPane().add(painelPalavra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed

        verificarPalpite(txtLetra.getText().charAt(0));
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForcaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForcaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForcaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForcaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForcaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel painelPalavra;
    private javax.swing.JTextField txtErros;
    private javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
